<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel='stylesheet' href="/stylesheets/bootstrap.css"/>
<link rel="stylesheet" href="/stylesheets/bootstrap-responsive.css"/>
<link rel='stylesheet' href="/stylesheets/style.css"/>
<script src="/js-lib/jquery/jquery-1.7.2.js"></script>
<script src="/js-lib/bootstrap/bootstrap.js"></script>
<style type="text/css">
    body {
        padding-top: 60px;
        padding-bottom: 40px;
    }
    #container{min-height:400px;}
</style>